#!/bin/bash

# https://tech.osteel.me/posts/docker-for-local-web-development-part-4-smoothing-things-out-with-bash

# source ./spinner.sh;
source ./colors.sh;
source ./functions.sh;

printServerLstOfCommands()
{
    echo -e "
 ${CYAN}Server command line interface for the Docker-based web development environment demo.

${YELLOW} Usage:${ENDCOLOR}
    demo <command> [options] [arguments]

${YELLOW} Available commands: ${ENDCOLOR}${GREEN}
    status ${BLUE}............................................................................${GREEN} Print status of containers
    start ${BLUE}.............................................................................${GREEN} Start the containers
    stop ${BLUE}..............................................................................${GREEN} Stop the containers
    restart [options] ${BLUE}.................................................................${GREEN} Restart the container
    pull ${BLUE}..............................................................................${GREEN} Pull the containers
    build [options] ${BLUE}...................................................................${GREEN} Build containers
                                                                                        Options:
                                                                                            --no-cache ${BLUE}................................${GREEN} Build no cache

    logs ${BLUE}..............................................................................${GREEN} Print logs of containers
    message-broker [command] ${BLUE}..........................................................${GREEN} Message broker
                                                                                        Options:
                                                                                            init ${BLUE}......................................${GREEN} Init
                                                                                            restart ${BLUE}...................................${GREEN} Restart
                                                                                            create-exchange [options] ${BLUE}.................${GREEN} Create RrabbitMQ Exchanges
                                                                                                                                        Options:
                                                                                                                                            command-handler ${BLUE}......................${GREEN} Command handler
                                                                                                                                            domain-event-handler ${BLUE}.................${GREEN} Domain Event handler

    bash ${BLUE}..............................................................................${GREEN} Containter interactive terminal bash
    cc ${BLUE}................................................................................${GREEN} Clear cache
    database [admin, client] [[seed], fresh, diff, migrate] ${BLUE}...........................${GREEN} Database
                                                                                        Options:
                                                                                            type ${BLUE}......................................${GREEN} Many actions

    artisan ${BLUE}...........................................................................${GREEN} Laravel Artisan commands
    composer ${BLUE}..........................................................................${GREEN} Composerz commands
    php-cs-fixer ${BLUE}......................................................................${GREEN} Php CS Fixer
    test [options] [arguments] ${BLUE}........................................................${GREEN} Run Test
                                                                                        Options:
                                                                                            -g, --group ${BLUE}...............................${GREEN} Filter by Group

    ${ENDCOLOR}
"
}

case "$1" in
    status)
        status
    ;;
    start)
        start ${@:2}
    ;;
    stop)
        stop
    ;;
    restart)
        restart ${@:2}
    ;;
    pull)
        pull
    ;;
    build)
        build ${@:2}
    ;;
    logs)
        logs ${@:2}
    ;;
    message-broker)
        message-broker ${@:2}
    ;;
    bash)
        bash
    ;;
    cc)
        cc
    ;;
    database)
        database ${@:2}
    ;;
    artisan)
        artisan ${@:2}
    ;;
    composer)
        composer ${@:2}
    ;;
    psalm)
        psalm ${@:2}
    ;;
    php-cs-fixer)
        php-cs-fixer ${@:2}
    ;;
    test)
        test ${@:2}
    ;;
    supervisor)
        supervisor ${@:2}
    ;;
    *)
        printServerLstOfCommands

        exit 1
    ;;
esac
