get:
  summary: Show product
  tags: 
    -  Products
  security: 
    -  bearerAuth: []
  parameters:
    - $ref: ../../../components/parameters/uuid.yml
  responses: 
    200:
      $ref: ../../../components/responses/admin/products/ShowProduct.yml

put:
  summary: Update product
  tags: 
    -  Products
  security: 
    -  bearerAuth: []
  parameters:
    - $ref: ../../../components/parameters/uuid.yml
  requestBody: 
    $ref: ../../../components/requestBodies/admin/products/Update.yml
  responses:
    202:
      $ref: ../../../components/responses/admin/products/UpdateProduct.yml

delete:
  summary: Delete product
  tags: 
    -  Products
  security: 
    -  bearerAuth: []
  parameters:
    - $ref: ../../../components/parameters/uuid.yml
  responses:
    204:
      $ref: ../../../components/responses/admin/products/DeleteProduct.yml
