get: 
  summary: Index
  tags: 
    - Roles
  security: 
    - bearerAuth: []
  parameters: 
    - $ref: ../../../components/parameters/query/page.yml
    - $ref: ../../../components/parameters/query/per_page.yml
    - $ref: ../../../components/parameters/query/search.yml
    - $ref: ../../../components/parameters/query/search_by.yml
    - $ref: ../../../components/parameters/query/sort_by.yml
    - $ref: ../../../components/parameters/query/is_sort_desc.yml
  responses:
    200:
      $ref: ../../../components/responses/admin/roles/Index.yml

post: 
  summary: Create
  tags: 
    -  Roles
  security: 
    -  bearerAuth: []
  requestBody: 
    $ref: ../../../components/requestBodies/admin/roles/Create.yml
  responses:
    201:
      $ref: ../../../components/responses/admin/roles/Create.yml
    
  
